# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.define "server-01" do |cfg|
    cfg.vm.network "private_network", ip: "192.168.101.11"
    cfg.vm.network "forwarded_port", guest: 80, host: 10081

    cfg.vm.provision "shell", inline: "hostnamectl set-hostname server-01"
    cfg.vm.provision "shell", path: "scripts/set-selinux-permissive.sh"
    cfg.vm.provision "shell", path: "scripts/init-zabbix-server.sh"
    cfg.vm.provision "shell", path: "scripts/init-zabbix-agent.sh", args: ["Zabbix server", "127.0.0.1"]
  end

  config.vm.define "agent-01" do |cfg|
    cfg.vm.network "private_network", ip: "192.168.101.21"
    cfg.vm.network "forwarded_port", guest: 80, host: 10083

    cfg.vm.provision "shell", inline: "hostnamectl set-hostname agent-01"
    cfg.vm.provision "shell", path: "scripts/set-selinux-permissive.sh"
    cfg.vm.provision "shell", path: "scripts/init-zabbix-agent.sh", args: ["agent-01", "192.168.101.11"]
    cfg.vm.provision "shell", path: "scripts/create-zabbix-host.sh", args: ["192.168.101.11", "agent-01", "192.168.101.21"]
  end

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "256"
    vb.linked_clone = true
  end
end
