# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "256"
  end

  config.vm.provision "shell", inline: "chmod -x /etc/update-motd.d/*"
 
  config.vm.define "a1" do |cfg|
    cfg.vm.hostname = "a1"
    cfg.vm.network "private_network", ip: "192.168.1.101", virtualbox__intnet: "net1"
    cfg.vm.network "private_network", ip: "192.168.2.101", virtualbox__intnet: "net2"

    cfg.vm.provision "shell", inline: "apt install -y openvpn"
    cfg.vm.provision "shell", inline: "openvpn --genkey --secret /vagrant/openvpnkey"

    cfg.vm.provision "shell", run: "always", inline: "sysctl net.ipv4.ip_forward=1"
    cfg.vm.provision "shell", run: "always", inline: "openvpn --remote 192.168.1.102 1194 udp --dev tun --secret /vagrant/openvpnkey --ifconfig 10.1.0.1 10.1.0.2 --route 192.168.3.0 255.255.255.0 vpn_gateway --writepid /run/openvpn/openvpn.pid --daemon"
  end

  config.vm.define "b1" do |cfg|
    cfg.vm.hostname = "b1"
    cfg.vm.network "private_network", ip: "192.168.1.102", virtualbox__intnet: "net1"
    cfg.vm.network "private_network", ip: "192.168.3.101", virtualbox__intnet: "net3"

    cfg.vm.provision "shell", inline: "apt install -y openvpn"

    cfg.vm.provision "shell", run: "always", inline: "sysctl net.ipv4.ip_forward=1"
    cfg.vm.provision "shell", run: "always", inline: "openvpn --remote 192.168.1.101 1194 udp --dev tun --secret /vagrant/openvpnkey --ifconfig 10.1.0.2 10.1.0.1 --route 192.168.2.0 255.255.255.0 vpn_gateway --writepid /run/openvpn/openvpn.pid --daemon"
  end

  config.vm.define "a2" do |cfg|
    cfg.vm.hostname = "a2"
    cfg.vm.network "private_network", ip: "192.168.2.102", virtualbox__intnet: "net2"

    cfg.vm.provision "shell", inline: "route del default"
    cfg.vm.provision "shell", inline: "route add default gw 192.168.2.101"
  end

  config.vm.define "b2" do |cfg|
    cfg.vm.hostname = "b2"
    cfg.vm.network "private_network", ip: "192.168.3.102", virtualbox__intnet: "net3"

    cfg.vm.provision "shell", inline: "route del default"
    cfg.vm.provision "shell", inline: "route add default gw 192.168.3.101"
  end
end
